spring:
  application:
    name: spring-cloud-pubsub
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true
  cloud:
    stream:
      bindings:
        hello-out-0:
          destination: hello-topic
        order-out-0:
          destination: order-events
      binders:
        pubsub:
          type: pubsub
      default-binder: pubsub
    gcp:
      project-id: ${GCP_PROJECT_ID:hello-world}
      pubsub:
        enabled: true
        emulator-host: localhost:8085
